[debug] [2023-02-04T21:16:15.820Z] ----------------------------------------------------------------------
[debug] [2023-02-04T21:16:15.822Z] Command:       B:\nodejs\node.exe C:\Users\caioa\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js hosting:disable
[debug] [2023-02-04T21:16:15.823Z] CLI Version:   11.22.0
[debug] [2023-02-04T21:16:15.823Z] Platform:      win32
[debug] [2023-02-04T21:16:15.823Z] Node Version:  v16.15.0
[debug] [2023-02-04T21:16:15.823Z] Time:          Sat Feb 04 2023 18:16:15 GMT-0300 (Horário Padrão de Brasília)
[debug] [2023-02-04T21:16:15.824Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-02-04T21:16:15.831Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/undefined [none]
[debug] [2023-02-04T21:16:16.555Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/undefined 403
[debug] [2023-02-04T21:16:16.556Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/undefined {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2023-02-04T21:16:16.556Z] HTTP Error: 403, The caller does not have permission
[debug] [2023-02-04T21:16:17.775Z] FirebaseError: HTTP Error: 403, The caller does not have permission
    at responseToError (C:\Users\caioa\AppData\Roaming\npm\node_modules\firebase-tools\lib\responseToError.js:49:12)
    at RetryOperation._fn (C:\Users\caioa\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:288:77)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[error] 
[error] Error: Failed to get Firebase project undefined. Please make sure the project exists and your account has permission to access it.
